export const stage2Fixture = {
  staffName: "Stage 2 E2E Staff",
  staffEmail: "stage-2-e2e@denk.local",
  staffPassword: "stage-2-e2e-password",
  restaurantName: "Stage 2 E2E Restaurant",
  tableName: "Stage 2 E2E Table",
  allocationTableName: "Stage 4 E2E Allocation Table",
  managedTableName: "Stage 3 E2E Managed Table",
  renamedManagedTableName: "Stage 3 E2E Renamed Table",
  catalogCategoryKey: "e2e-breakfasts",
  catalogCategoryName: "Breakfasts",
  catalogItemKey: "e2e-shared-breakfast",
  catalogItemName: "E2E Shared Breakfast",
  catalogItemPriceMinor: 12_550,
} as const;
